version = 0.1

[staging.deploy.parameters]
stack_name = "staging-todo-list-aws"
resolve_s3 = true
capabilities = ["CAPABILITY_IAM"]
disable_rollback = false
confirm_changeset = false
fail_on_empty_changeset = false

[staging.deploy.parameters.parameter_overrides]
Stage = "staging"

[staging.global.parameters]
region = "us-east-1"